2025-02-16 12:14:55 [149010] DEBUG
matplotlib: matplotlib data path: /home/sai-lokesh/.local/lib/python3.12/site-packages/matplotlib/mpl-data

2025-02-16 12:14:55 [149010] DEBUG
matplotlib: CONFIGDIR=/home/sai-lokesh/.config/matplotlib

2025-02-16 12:14:55 [149010] DEBUG
matplotlib: interactive is False

2025-02-16 12:14:55 [149010] DEBUG
matplotlib: platform is linux

2025-02-16 12:14:55 [149010] DEBUG
matplotlib: CACHEDIR=/home/sai-lokesh/.cache/matplotlib

2025-02-16 12:14:55 [149010] DEBUG
matplotlib.font_manager: font search path [PosixPath('/home/sai-lokesh/.local/lib/python3.12/site-packages/matplotlib/mpl-data/fonts/ttf'), PosixPath('/home/sai-lokesh/.local/lib/python3.12/site-packages/matplotlib/mpl-data/fonts/afm'), PosixPath('/home/sai-lokesh/.local/lib/python3.12/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts')]

2025-02-16 12:14:58 [149010] INFO
matplotlib.font_manager: Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Can not load face (unknown file format; error code 0x2)

2025-02-16 12:15:00 [149010] WARNING
matplotlib.font_manager: Matplotlib is building the font cache; this may take a moment.

2025-02-16 12:15:01 [149010] INFO
matplotlib.font_manager: generated new fontManager

2025-02-16 12:15:02 [149010] DEBUG
pip._internal.utils.unpacking: bz2 module is not available

2025-02-16 12:15:02 [149010] DEBUG
pip._internal.utils.unpacking: lzma module is not available

2025-02-16 12:15:02 [149010] DEBUG
pip._internal.vcs.versioncontrol: Registered VCS backend: bzr

2025-02-16 12:15:02 [149010] DEBUG
pip._internal.vcs.versioncontrol: Registered VCS backend: git

2025-02-16 12:15:02 [149010] DEBUG
pip._internal.vcs.versioncontrol: Registered VCS backend: hg

2025-02-16 12:15:02 [149010] DEBUG
pip._internal.vcs.versioncontrol: Registered VCS backend: svn

